let a="30 Days Of JavaScript";
console.log(a);
console.log(a.length);
console.log(a.toUpperCase());
console.log(a.toLowerCase());
console.log(a.substr(0,2));
console.log(a.substring(0,2));
console.log(a.includes("Script"));
console.log(a.split(" "));
console.log(a.split(""));
let b="Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon";
console.log(b.split(", "));
console.log(a.replace("JavaScript", "Python"));
console.log(a.charAt(15));
console.log(a.charCodeAt(11));
console.log(a.indexOf("a"));
console.log(a.lastIndexOf("a"));
let c="Bir cümleyi çünkü ile bitiremezsiniz çünkü çünkü bir bağlaçtır";
console.log(c.indexOf("çünkü"));
console.log(c.lastIndexOf("çünkü"));
console.log(c.search("çünkü"));
console.log(a.trim());
console.log(a.startsWith("30"));
console.log(a.endsWith("Script"));
console.log(a.match(/a/g));
console.log(a.concat(" - Learn JavaScript"));
console.log(a.repeat(2));